### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/handbook#18]

**Comment by abitsalihu** [comment]
Hey , I would like to help on this issue. :)

**Comment by kbdharun** [comment]
Actually, We already added this post. This issue was created to update the documentation progress chart https://github.com/orgs/Vanilla-OS/projects/2/views/1 . We are waiting for the next ISO to work on a post for `apx`.  You can coordinate with us in the #docs-writing channel in Discord.
