### ISSUE TITLE
Guide for installing Jekyll & Bundler 

### ISSUE THREAD

**Issue by gonzoknows** [Vanilla-OS/handbook#41]
Guide for installing & uninstalling Jekyll & Bundler

For how easy it sounds, on an distro like this I haven't figured it out. Even for my own website, I push changes straight to the main repo without running locally. Though I would love a guide to run the changes locally and I'm sure many other vanilla os users would to. I've got it to work once but forgot how to. I believe my steps were as followed 

1. apx init 
2. apx enter
3. sudo apt-get install ruby-full build-essential zlib1g-dev
4. sudo gem install jekyll bundler
5. cd repo 
6. sudo bundler install

**Comment by kbdharun** [comment]
I will work on this soon because I use both in Vanilla. Now, I have some other posts to write.
