### ISSUE TITLE
Add basics of nix to the handbook

### ISSUE THREAD

**Issue by pulkitkrishna00** [Vanilla-OS/handbook#77]
I know there are plenty of resources for nix, but most of them are aimed at one particular configuration and use case of nix. It would be better if some basics of nix are covered in the handbook or somewhere.

**Comment by MonsterObserver** [comment]
Closing this for now since the goal of Nix on Vanilla OS is just to get binaries on the system. Feel free to reopen with a more in-depth explanation of things you'd like to see added.
